version: 0.2

phases:
  install:
    commands:
      # Install dependencies
      - echo Installing dependencies...
      - mvn install -DskipTests

  build:
    commands:
      # Build the project
      - echo Building the project...
      - mvn package -DskipTests

  post_build:
    commands:
      # Run unit tests
      - echo Running unit tests...
      - mvn test

artifacts:
  files:
    - target/*.jar  # Uploads the JAR file to S3 (if you have configured S3 artifacts)

cache:
  paths:
    - '/root/.m2/**/*'  # Caching Maven dependencies for faster builds
